include:
  - 'docker-compose.yml'

services:
  bruno:
    build:
      context: '../'
      dockerfile: './support/Dockerfile'
    environment:
      - 'NODE_ENV=test'
    volumes:
      - '.tmp/sailsWorkingDir/tmp:/opt/redbox-portal/.tmp'
      - '.tmp/attachments:/attachments'
      - '../:/opt/sails-hook-redbox-pdfgen'
    networks:
      main:
        aliases:
          - 'bruno'
    depends_on:
      rbportal:
        condition: 'service_healthy'
    entrypoint: >-
      /bin/bash -c "
      cd /opt/sails-hook-redbox-pdfgen &&
      npm install -g @usebruno/cli &&
      cd /opt/sails-hook-redbox-pdfgen/test/bruno &&
      bru run
      --env test
      --format junit
      --output /opt/sails-hook-redbox-pdfgen/support/.tmp/junit/backend-bruno/backend-bruno.xml
      --bail"
