include:
  - 'docker-compose.yml'

services:
  bruno:
    image: 'qcifengineering/redbox-portal:v3.7'
    environment:
      - 'NODE_ENV=test'
    volumes:
      - '../:/opt/sails-hook-redbox-pdfgen'
    networks:
      main:
        aliases:
          - 'bruno'
    depends_on:
      rbportal:
        condition: 'service_healthy'
    entrypoint: >-
      /bin/bash -c "
      cd /opt/sails-hook-redbox-pdfgen &&
      npm install -g @usebruno/cli &&
      cd /opt/sails-hook-redbox-pdfgen/test/bruno &&
      bru run
      --env test
      --format junit
      --output /opt/sails-hook-redbox-pdfgen/support/tmp-data/junit/backend-bruno/backend-bruno.xml
      --bail"
