networks:
  main:

services:

  minio:
    image: 'quay.io/minio/minio:RELEASE.2024-07-29T22-14-52Z'
    command: 'server /data --console-address ":9002"'
    expose:
      - '9000'
      - '9002'
    ports:
      - '9000:9000'
      - '9002:9002'
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
    volumes:
      - '.tmp/minio-data:/data'
    healthcheck:
      test: [ 'CMD-SHELL', 'curl http://localhost:9000' ]
      interval: '5s'
      timeout: '5s'
      retries: '10'
      start_period: '20s'
    networks:
      main:
        aliases:
          - 'minio'

  rbportal:
    build:
      context: '../'
      dockerfile: './support/Dockerfile'
    expose:
      - '1500'
    ports:
      - '1500:1500'
    environment:
      - 'NODE_ENV=docker'
      - 'sails_log__level=verbose'
      - 'PORT=1500'
      - 'sails_admin__api_token=6b088b4d-d54c-470c-8568-2f2695fcdab9'
      - 'sails_auth__default__local__default__token=6b088b4d-d54c-470c-8568-2f2695fcdab9'
      - 'sails_auth__default__local_pdfbot_token=6b088b4d-d54c-470c-8568-2f2695fcdab9'
      - 'sails_record__baseUrl__mint=https://demo.redboxresearchdata.com.au/mint'
      - 'HOOK_S3_ACCESS_KEY=minioadmin'
      - 'HOOK_S3_SECRET_KEY=minioadmin'
      - 'HOOK_S3_REGION=ap-southeast-2'
      - 'HOOK_S3_BUCKET=attachments'
      - 'HOOK_S3_ENDPOINT=http://minio:9000'
    volumes:
      - '.tmp/sailsWorkingDir/tmp:/opt/redbox-portal/.tmp'
      - '.tmp/attachments:/attachments'
      - '../:/opt/sails-hook-redbox-pdfgen'
    healthcheck:
      test: [ 'CMD-SHELL', 'curl http://localhost:1500' ]
      interval: '5s'
      timeout: '5s'
      retries: '10'
      start_period: '30s'
    networks:
      main:
        aliases:
          - 'rbportal'
    depends_on:
      minio:
        condition: 'service_healthy'
      mongodb:
        condition: 'service_healthy'
      solr:
        condition: 'service_healthy'
    entrypoint: >-
      /bin/bash -c "
      /opt/sails-hook-redbox-pdfgen/support/prepare-guest.sh &&
      cd /opt/redbox-portal &&
      node app.js"

  mongodb:
    image: 'mongo:6'
    expose:
      - '27017'
    ports:
      - '27017:27017'
    volumes:
      - '.tmp/mongo:/data/db'
    healthcheck:
      test: [ 'CMD-SHELL', "echo 'db.runCommand(\"ping\").ok' | mongosh" ]
      interval: '5s'
      timeout: '5s'
      retries: '10'
      start_period: '30s'
    networks:
      main:
        aliases:
          - 'mongodb'

  solr:
    image: 'solr:8.11.1'
    expose:
      - '8983'
    ports:
      - '8983:8983'
    environment:
      - 'SOLR_HOME=/var/solr/data'
    volumes:
      - '.tmp/solr:/var/solr/data'
    healthcheck:
      test: [ 'CMD-SHELL', 'curl http://localhost:8983' ]
      interval: '5s'
      timeout: '5s'
      retries: '10'
    networks:
      main:
        aliases:
          - 'solr'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - redbox
