
include:
  - 'docker-compose.yml'

services:
  mocha:
    image: 'qcifengineering/redbox-portal:v3.7'
    environment:
      - 'NODE_ENV=test'
    volumes:
      - '../:/opt/sails-hook-redbox-pdfgen'
    networks:
      main:
        aliases:
          - 'mocha'
    depends_on:
      rbportal:
        condition: 'service_healthy'
    entrypoint: >-
      /bin/bash -c "
      cd /opt/sails-hook-redbox-pdfgen &&
      npm install &&
      node_modules/.bin/mocha"
