version: 2.1

jobs:
  build:
    docker:
      # docker image version must match version in .nvmrc
      - image: cimg/node:20.15.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ .Branch }}
            - v1-node
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build this package
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Run Bruno and Mocha tests
          command: |
            npm run dev:host
            npm run test:bruno:docker
            npm run test:bruno:docker:clean
            npm run test:mocha:docker
            npm run test:mocha:docker:clean

  publish:
    docker:
      # docker image version must match version in .nvmrc
      - image: cimg/node:20.15.0
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  build_and_publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
