version: 2.1

jobs:
  build:
    docker:
      # docker image version must match version in .nvmrc
      - image: cimg/node:20.15.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ .Branch }}
            - v1-node
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Compile the typescript
          command: npm run compile:tsc
      - save_cache:
          key: v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    environment:
      BUILDKIT_PROGRESS: 'plain'
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Change project dir ownership to work in docker container
          command: sudo chown -R 1000:1000 /home/circleci/project
      - run:
          name: Prepare the host machine
          command: npm run dev:host
      - run:
          name: Run Bruno and Mocha tests
          command: |
            npm run test:bruno:docker
            npm run test:bruno:docker:clean

# TODO: get the mocha / puppeteer tests working
#npm run test:mocha:docker
#npm run test:mocha:docker:clean

  publish:
    docker:
      # docker image version must match version in .nvmrc
      - image: cimg/node:20.15.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ .Branch }}
            - v1-node
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Compile the typescript
          command: npm run compile:tsc
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public
      - save_cache:
          key: v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

workflows:
  build_and_publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
