version: 2.1

jobs:
  build:
    docker:
      # docker image version must match version in .nvmrc
      - image: cimg/node:20.15.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ .Branch }}
            - v1-node
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Compile typescript
          command: node_modules/.bin/tsc
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      # docker image version must match version in .nvmrc
      - image: cimg/node:20.15.0
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
