version: '3.4'

networks:
  main:

services:

  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-29T22-14-52Z
    container_name: minio
    command: server /data --console-address ":9002"
    expose:
      - "9000"
      - "9002"
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    hostname: minio
    volumes:
      - .tmp/minio-data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9000"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      main:
        aliases:
          - minio

  rbportal:
    container_name: rbportal
#    image: qcifengineering/redbox-portal:develop
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "1500:1500"
    volumes:
      - "./.tmp/sailsWorkingDir/tmp:/opt/redbox-portal/.tmp"
      - "./.tmp/attachments:/attachments"
      - "../../:/opt/sails-hook-redbox-pdfgen"
    expose:
      - "1500"
    environment:
      - NODE_ENV=docker
      - sails_log__level=verbose
      - PORT=1500
      - sails_admin__api_token=6b088b4d-d54c-470c-8568-2f2695fcdab9
      - sails_auth__default__local__default__token=6b088b4d-d54c-470c-8568-2f2695fcdab9
      - sails_auth__default__local_pdfbot_token=6b088b4d-d54c-470c-8568-2f2695fcdab9
      - sails_record__baseUrl__mint=https://demo.redboxresearchdata.com.au/mint
      - sails_session__adapter=mongo
      - sails_sesssion_url=mongodb://mongodb:27017/redbox-portal
      - HOOK_S3_ACCESS_KEY=minioadmin
      - HOOK_S3_SECRET_KEY=minioadmin
      - HOOK_S3_REGION=ap-southeast-2
      - HOOK_S3_BUCKET=attachments
      - HOOK_S3_ENDPOINT=http://minio:9000
    networks:
      main:
        aliases:
          - rbportal
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:1500"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      minio:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      solr:
        condition: service_healthy
    entrypoint: >-
      /bin/bash -c "
      chmod +x /opt/sails-hook-redbox-pdfgen/support/development/prepare-minio.sh &&
      /opt/sails-hook-redbox-pdfgen/support/development/prepare-minio.sh &&
      cd /opt/sails-hook-redbox-pdfgen &&
      npm run build &&
      mkdir -p /tmp/build-sails-hook-redbox-pdfgen &&
      rm -rf /tmp/build-sails-hook-redbox-pdfgen/researchdatabox-sails-hook-redbox-pdfgen* &&
      npm pack . --pack-destination=/tmp/build-sails-hook-redbox-pdfgen &&
      cd /opt/redbox-portal &&
      npm install /tmp/build-sails-hook-redbox-pdfgen/researchdatabox-sails-hook-redbox-pdfgen* &&
      node app.js"

  mongodb:
    container_name: mongodb
    image: mongo:6
    networks:
      main:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
    volumes:
      - ".tmp/mongo:/data/db"
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s

  solr:
    container_name: solr
    image: solr:8.11.1
    networks:
      main:
        aliases:
          - solr
    expose:
      - "8983"
    ports:
      - "8983:8983"
    environment:
      - SOLR_HOME=/var/solr/data
    volumes:
      - ".tmp/solr:/var/solr/data"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8983"]
      interval: 5s
      timeout: 5s
      retries: 10
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - redbox
