version: '3.1'

networks:
  main:

services:

  redboxportal:
    image: qcifengineering/redbox-portal:develop
    ports:
      - "1500:1500"
    volumes:
      - "../../:/opt/sailshook"
      - "../../sailsWorkingDir/tmp:/opt/redbox-portal/.tmp"
    expose:
      - "1500"
    environment:
      - NODE_ENV=docker
      - PORT=1500
      - sails_record__baseUrl_redbox=http://redbox:9000/redbox
      - sails_record__baseUrl_mint=http://203.101.226.160/mint
    networks:
      main:
        aliases:
          - rbportal
    entrypoint: /bin/bash -c "source /opt/sailshook/support/development/linkHook.sh"

  mongodb:
    image: mongo:latest
    networks:
      main:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
